import Head from "next/head";

import Heading from "@/components/Heading";
import ProjectCard from "@/components/ProjectCard";
import { projects } from "@/config/projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-between bg-gradient-to-br from-slate-800 to-black p-0 pb-24">
        <Heading />
        <div className="p-10 mt-12 grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 grid-rows-3 h-screen">
          {projects.map((project, idx) => (
            <ProjectCard data={project} key={idx} />
          ))}
        </div>
      </main>
    </>
  );
}
